spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Admin
    url: jdbc:mysql://localhost:3306/JWT-DATABASE?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 	
